---

- name: ura.ini template
  template: src=ura.ini.j2 dest=/var/www/ura.ini mode=0666 owner=root group=root
  tags:
  - ura.ini

- name: upload admin files
  copy: src=ura/admin dest="{{ura_webroot}}"
  tags:
  - admin

- name: upload xpc-ca files
  copy: src=ura/xpc-ca dest="{{ura_webroot}}"
  tags:
  - xpc-ca

- name: upload eduroam files
  copy: src=ura/eduroam dest="{{ura_webroot}}"
  tags:
  - eduroam

